### ISSUE TITLE
Error running make

### ISSUE THREAD

**Issue by danifitz** [newrelic/nri-network-telemetry#3]
Hi - when I run make, I get an error:

`ERRO Running error: context loading failed: failed to load program with go/packages: internal error: go list gives conflicting information for package nri-network-telemetry/vendor/github.com/newrelic/nri-network-telemetry/internal/util 
make: *** [lint] Error 3`

**Comment by melzreal** [comment]
tried this after googling around and hitting the same problem:

run
 go  env -w GO111MODULE="on"

reason for that error seemed to be, when doing "go env " that module was set to empty.
Now I'm seeing different errors so well, that's progress.

**Comment by melzreal** [comment]
so disregard the above since the error following that -  github.com/fsnotify/fsnotify@v1.4.7 used for two different module paths (github.com/fsnotify/fsnotify and gopkg.in/fsnotify.v1)
make: *** [tools] Error 1

got me down a rabbit hole saying modules shouldn't be used, and github links should be used instead so that variable should stay off - https://github.com/golang/go/issues/26904

as per "Agnivade's" comment on that thread. 

So just stumped here

**Comment by jthurman42** [comment]
This repo previously did not use go modules for dependencies (it used `dep`).  I've migrated to modules in the latest release, as well as added in CircleCI builds to confirm.

Please retest with:
* Golang 1.13.0+
* Cleaned repo / pull from `master` or release tag `v1.0.0`

**Comment by danifitz** [comment]
Thanks @jthurman42 this works for me now with golang v1.13
